# Generated by Django 2.0.2 on 2018-02-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180222_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='昵称'),
        ),
    ]
