# Generated by Django 2.0.2 on 2018-02-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180224_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner/%Y/%m', verbose_name='轮播图'),
        ),
    ]
