# Generated by Django 2.0.2 on 2018-03-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180224_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannercourse',
            options={'verbose_name': '首页课程', 'verbose_name_plural': '首页课程'},
        ),
        migrations.AlterField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否放在首页'),
        ),
    ]
