# Generated by Django 2.0.2 on 2018-03-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180307_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.TextField(default='', max_length=200, verbose_name='访问地址'),
        ),
    ]
