# Generated by Django 2.0.2 on 2018-03-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180313_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.TextField(default='', verbose_name='访问地址'),
        ),
    ]
